### ISSUE TITLE
You need to reset the current step

### ISSUE THREAD

**Issue by axeldomingues** [MartinThoma/banana-gym#4]
https://github.com/MartinThoma/banana-gym/blob/a6f16be8bed58e01d688a9ab4577b281bbed2a14/gym_banana/envs/banana_env.py#L140

You need to reset the current step otherwise this environment is doing nothing.

**Comment by MartinThoma** [comment]
Thank you! Do you want to create a PR? Otherwise, I'll just fix it after work :-)

**Comment by axeldomingues** [comment]
Sure will open a PR for it. Cheers.
