### ISSUE TITLE
import gym_banana in colab gives ModuleNotFoundError

### ISSUE THREAD

**Issue by thirdreplicator** [MartinThoma/banana-gym#6]
I tried to install gym_banana in colab, but I'm getting a ModuleNotFoundError. I tried different ways.. 
Frist try:
!git clone  https://github.com/MartinThoma/banana-gym.git
python ./banana-gym/setup.py install -e

Second try:
!pip install gym_banana

Both ways seem to work:
Requirement already satisfied: gym_banana in /usr/local/lib/python3.6/dist-packages/gym_banana-0.0.1-py3.6.egg (0.0.1)
Requirement already satisfied: gym>=0.2.3 in /usr/local/lib/python3.6/dist-packages (from gym_banana) (0.10.11)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from gym_banana) (0.24.2)
Requirement already satisfied: cfg_load in /usr/local/lib/python3.6/dist-packages (from gym_banana) (0.8.0)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.6/dist-packages (from gym>=0.2.3->gym_banana) (2.21.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.6/dist-packages (from gym>=0.2.3->gym_banana) (1.16.4)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from gym>=0.2.3->gym_banana) (1.12.0)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python3.6/dist-packages (from gym>=0.2.3->gym_banana) (1.4.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from gym>=0.2.3->gym_banana) (1.3.0)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas->gym_banana) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/dist-packages (from pandas->gym_banana) (2.5.3)
Requirement already satisfied: mpu[io]>=0.15.0 in /usr/local/lib/python3.6/dist-packages (from cfg_load->gym_banana) (0.19.0)
Requirement already satisfied: PyYAML>=4.2b1 in /usr/local/lib/python3.6/dist-packages (from cfg_load->gym_banana) (5.1.1)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->gym>=0.2.3->gym_banana) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->gym>=0.2.3->gym_banana) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->gym>=0.2.3->gym_banana) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->gym>=0.2.3->gym_banana) (2.8)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyglet>=1.2.0->gym>=0.2.3->gym_banana) (0.16.0)
Requirement already satisfied: tzlocal; extra == "io" in /usr/local/lib/python3.6/dist-packages (from mpu[io]>=0.15.0->cfg_load->gym_banana) (1.5.1)

I restarted the runtime then tried to import it in another cell:

import gym
import gym_banana

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-97fba099a95f> in <module>()
      1 import gym
----> 2 import gym_banana
      3 #env = gym.make('Banana-v0')

ModuleNotFoundError: No module named 'gym_banana'

**Comment by MartinThoma** [comment]
I'm not convinced that this is a problem with banana-gym. Seems rather to be a problem with the environment. I'm also not sure how to reproduce this.

**Comment by MartinThoma** [comment]
Do you think it would help if I uploaded it to PyPI so that you can install it without cloning?

**Comment by thirdreplicator** [comment]
Hi, thanks for the offer. I'm going to try installing banana-gym, and a
"hello world" module on my desktop and on colab and compare the two. I'll
let you know. I suspect that it has nothing to do with banana-gym and me
just being new to Colab.

**Comment by MartinThoma** [comment]
It's now on PyPI: https://pypi.org/project/gym-banana/ :-)

**Comment by thirdreplicator** [comment]
The directory gym_banana is not being copied to site-packages. I manually
copied it and then I was able to get the import statement to work on my
desktop. I think your setup.py needs to be modified maybe.

**Comment by MartinThoma** [comment]
Ah, that might have been the issue: https://github.com/MartinThoma/banana-gym/commit/709b7aedf85c95f2dbf62d57dc4db69a7acb92b9 - thank you! (A new version was released)

**Comment by thirdreplicator** [comment]
Yes that did it. It works on both my desktop and colab (after "pip
uninstall"-ing it first).
Great!
